const mongoose = require('mongoose');

// Single-use token that lets a customer add items to an existing order.
// Generated by an admin and shared via a private link.
const orderAddTokenSchema = new mongoose.Schema({
    token: { type: String, required: true, unique: true, index: true },
    targetType: { type: String, enum: ['order', 'gb-cart'], required: true },
    targetOrderId: { type: mongoose.Schema.Types.ObjectId, ref: 'Order' }, // for in-stock
    targetCartOrderCode: { type: String }, // for GB cart
    targetCartCheckoutId: { type: String }, // for GB cart
    targetUserId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    shippingAddress: {
        fullName: String, phone: String, street: String,
        city: String, province: String, postalCode: String, zipCode: String
    },
    expiresAt: { type: Date, required: true },
    usedAt: { type: Date, default: null },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

module.exports = mongoose.model('OrderAddToken', orderAddTokenSchema);
